name: Build Installers

on:
  workflow_dispatch:

env:
  APP_RELEASE_VERSION: ${{ vars.APP_RELEASE_VERSION }}

jobs:
  build-linux-installer:
    name: Build Installer on Linux
    runs-on: ubuntu-latest
    steps:
      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21

      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          sh build-linux-release.sh

      # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: ./build/distributions/basic4glj_{{ vars.APP_RELEASE_VERSION }}_amd64.deb
          name: linux-installer
          retention-days: 1

  build-windows-installer:
    name: Build Installer on Windows
    runs-on: windows-latest
    steps:
      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21

      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          sh build-windows-release.sh

      # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: ./build/distributions/Basic4GLj-${{ vars.APP_RELEASE_VERSION }}.msi
          name: windows-installer
          retention-days: 1

  build-macos-installer:
    name: Build Installer on MacOS
    runs-on: macos-latest
    steps:
      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21

      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          sh build-mac-release.sh

      # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: ./build/distributions/Basic4GLj-${{ vars.APP_RELEASE_VERSION }}.dmg
          name: macos-installer
          retention-days: 1
